// <auto-generated />
namespace ClothBazar.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialised : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialised));
        
        string IMigrationMetadata.Id
        {
            get { return "202011041136076_initialised"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
